### ISSUE TITLE
Plugin for password managers

### ISSUE THREAD

**Issue by db-k9mail** [k9mail/k-9-design#10]
Keep your passwords to your mailproviders stored savely in the password manager of your choice.

**Comment by philipwhiuk** [comment]
Is there an existing API that password manager's expose that we could implement? That seems like the first step in this - for them to provide APIs for other apps to use.

We'll need the password without user interaction however - we use it asynchronously in the background to poll and subscribe to push events.

**Comment by rugk** [comment]
Also this is not a design issue, better create an issue in the main repo.

**Comment by db-k9mail** [comment]
> Also this is not a design issue, better create an issue in the main repo.

Oh, sry ... I thought of "design" in terms of program architecture. My bad. Simply close this and the other request then.
