### ISSUE TITLE
A bit more color

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9-design#3]
Currently everything looks so grey or b/w in your mockups…

A bit more colour would be nice…
I mean your app should also be differentiable to other mail apps and not only "just another mail app". It should be "K9, yeah!"… :tada: :smiley:

**Comment by juliakorbut** [comment]
You can take a look here - there are two themes (dark and light) and different account colors that mix with those themes: https://github.com/k9mail/k-9-design/blob/master/Flows/K-9%20-%20Account%20Colors%20and%20Themes.png this is meant to be modular, so it's as  🎉 as you'd want it to be!
