### ISSUE TITLE
improvement suggestion: Use different icon for "add new E-mail account"

### ISSUE THREAD

**Issue by conrad-heimbold** [k9mail/k-9-design#5]
When I am on the E-mail-account overview screen, I always confuse the "compose new e-mail"- with the "add new e-mail-account"-button. 
That's mainly because the plus for "add new e-mail-account" is much bigger than the one in "compose new e-mail".

Therefore, I would suggest to use a different icon for "add new e-mail-account". 
I already designed different variations of such an icon. They are inspired by german / british / european postal mailboxes. They also include a post horn (just like the German postal company "Deutsche Post" uses a stylised one, look for "Deutsche Post icon" on Google.). 

You can find my suggestions here: 
https://gist.github.com/conrad-heimbold/8e61182610c6116546347e292d6d8826 

They are in svg format. If you want them in png, just open them in Inkscape and export them as png. 

Post horns were used by mail carriers; just like floppy disks were used in the past. 
Floppy disks are still used as symbol for saving files, so I would like to use posthorns/mailboxes as symbol for e-mail-accounts. 

Please feel free to make improvements to these icons. 
I did not yet figure out how to make the white parts completely transparent (you should see the background through transparent parts, not other borders / parts).

**Comment by rugk** [comment]
I second the general idea, but posthorns, no ehm… In contrast to floppy disks it is just not common and in small sizes I'd say the icons you linked are also rather unreadable. But to let the icons differ a bit more is a good idea in general.

**Comment by conrad-heimbold** [comment]
What a pity, I thought I had a creative idea.... I made a google search; and apparantly nobody ever had the idea to use a posthorn. 
Anyway, if you don't like the posthorn, you can leave it out and just style a postal mailbox without them. Such mailboxes should be recognized. 
I am not very good with styling in inkscape, please feel free to improve.

**Comment by conrad-heimbold** [comment]
I made some mailboxes without posthorn. 
They are in svg format, so for icon sizes larger than 32x32 pixels, they should be perfectly recognizable. 
Have a look here: 
https://gist.github.com/conrad-heimbold/572636a716fafb482ff1d89aae89ecae

**Comment by rugk** [comment]
It's indeed a creative idea, but I don't know whether it can be used in a meaningful way in such an icon.
Maybe somebody else with a better understanding of design has some ideas.

**Comment by conrad-heimbold** [comment]
Let's wait for @juliakorbut s answers / suggestions .

**Comment by juliakorbut** [comment]
Hey Conrad! That's good feedback. Just so I understand correctly, your suggestion is for there to be a fab with this icon, that will essentially add a new account?

Where do you envision it being in this flow?
https://raw.githubusercontent.com/k9mail/k-9-design/master/Flows/K-9%20-%20Entire%20App.jpg

The way I modeled this is for new accounts to be added by tapping the plus (+)
sign here, similar to native Google apps:
https://github.com/k9mail/k-9-design/blob/master/Screens/Drawer@3x.png

**Comment by juliakorbut** [comment]
Also, do you find yourself needing to add accounts a lot as part of your workflow?

**Comment by cketti** [comment]
I believe the confusion is with the current app, not the proposed design. It's a common complaint. But we don't intend to "fix" the icon before the UI redesign.

Moving the "add account" icon to the account switcher in the drawer should make it very clear that this plus icon is for adding accounts, not composing a new message. But "add account" is only very rarely used, so maybe we should do it like Gmail and "hide" the action in the expanded account switcher. Then there's also room for text which should help to reduce any potential confusion. 

![gmail_add_account](https://cloud.githubusercontent.com/assets/218061/24569903/c5fb0ec8-1668-11e7-81e3-d43887aaf34b.png)

@conrad-heimbold Considering we're very likely to go with https://github.com/k9mail/k-9-design/blob/master/Screens/Drawer@3x.png or do it similar to Gmail (displayed in the screenshot above) in a future version of K-9 Mail, do you still believe a change of icon is necessary?

**Comment by conrad-heimbold** [comment]
Yes, my suggestion was actually only meant for the "old" design / "old" k9mail-app. For the future design, it doesn't apply anymore (probably). However, as the stable implementation of this design here might still take a while, we could use such an icon as a quick fix for k9mail. Shouldn't be too difficult. I already tried the unofficial K9Mail-Client with Material Design by @scoute-dich , however, it didn't seem to be quite stable (crashed multiple times, unfortunately). 
Yes, you are right, I don't use the "add e-mail-account"-button very often in normal workflow. 

Off-topic: I have to admit, that I like combining multiple icons into one to make the meaning more clear. e.g. 
pen + E-mail = edit E-mail
plus sign + mailbox = add new e-mail account. 
With todays screen pixel densities on phones, I think you can still recognize both symbols very good.

**Comment by conrad-heimbold** [comment]
Because @cketti said: "We don't intend to fix the icon before the UI redesign", I think this bug should be closed.
