### ISSUE TITLE
Needs more colors

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9-design#8]
From randomly checking out some images in this repo, I noticed they are all black text on white background. This is not only boring, but you cannot identify K9mail as a strong "corporate identity", if you see what I mean.

Do you even have a accent/highlight color? If so, where is it used? (I always see b/w only…)

For some reason even @moctodot mockups [here](https://github.com/k9mail/k-9/issues/1859#issue-196752930), whcih only use some slight gray, already make it appear less boring as it does not look like a white empty plain :desert: then…

In general, do you have a color concept as @moctodot did there?

**Comment by cketti** [comment]
Your post sounds very confrontational and dismissive of the work of a volunteer (again). Please try to be more considerate when posting.

Being colorful and having a strong "corporate identity" is not something that's important to me. Fitting in to the platform and having a good user experience is.
Also, I think our time can be better spent than discussing minor details of early stage design drafts. Unless you can point out design flaws that impact UX, have concrete suggestions for improving UX, or want to provide alternative designs, please to to avoid creating additional issues in this repository.

You probably missed this: https://github.com/k9mail/k-9-design/blob/master/Screens/Settings%20-%20profile%401x.png

**Comment by rugk** [comment]
Oh wow, I indeed [missed this](https://github.com/k9mail/k-9-design/blob/master/Screens/Settings%20-%20profile%401x.png). Then I take back my criticism. If you can adjust the design, that makes it more colorful indeed. You may still think about a default color, but the idea is nice, IMHO.

BTW I am not dismissing any work, but just saying what I think about the design and compare it with other volunteer work. And it is completely legitimate to find a work of one volunteer, better than one of another one, IMHO.
