### ISSUE TITLE
Plugin for mail stores

### ISSUE THREAD

**Issue by db-k9mail** [k9mail/k-9-design#9]
I'd like to see a plugin for mailstore services.
Have your mailstore local or remote, encrypted or not by deploying/using the mailstore provider of your choice.
Example: https://github.com/google/jimfs based on the java.nio.file abstract file system APIs.

**Comment by philipwhiuk** [comment]
I'm not quite sure how JIMFs would be a viable replacement to an SQLite database. (Nor that JIMFS even runs on Android). Nor am I clear on the benefits of making the local store replaceable. The local store has to be responsive - we can't really be sending Intents to other apps for every refresh.

Having the RemoteStore as a plugin is something we've discussed (especially in terms of keeping K-9 unreliant on closed/partially closed protocols).

But there's not lots and lots of things you could plug-in (and Android doesn't really have a 'plug-ins as apps' philosophy). So the benefit of this is minimal.

**Comment by rugk** [comment]
Also this is not a design issue, better create an issue in the main repo.

**Comment by db-k9mail** [comment]
jimfs is an example of how to implement the java.nio.file abstract file system APIs.
Sure, it is possible to map database access to the API.
This means, with a file system API  you are free to provide a responsive API or a secure one (which might be less responsive). In the end, it's the users decision to plugin one store or the other.
On the other hand, you are free to patronize users the way you like.

Just my 2ct.

> Also this is not a design issue, better create an issue in the main repo.

Sry again (see the other thread) and simply close this issue.
